// Initial load actions
export const INITIAL_LOAD = "INITIAL_LOAD";
export const INITIAL_CATEGORIES_LOAD = "INITIAL_CATEGORIES_LOAD";
export const INITIAL_SORT = "INITIAL_SORT";
export const INITIAL_PRODUCT_TYPES_LOAD = "INITIAL_PRODUCT_TYPES_LOAD";
export const INITIAL_TOP25_LOAD = "INITIAL_TOP25_LOAD";
export const WAS_LOGGED_IN = "WAS_LOGGED_IN";

// add new start up actions
export const SUCCESSFUL_STARTUP_SUBMIT = "SUCCESSFUL_STARTUP_SUBMIT";
export const FAILED_STARTUP_SUBMIT = "FAILED_STARTUP_SUBMIT";

// Auth actions
export const LOG_OUT = "LOG_OUT";
export const SUCCESSFUL_LOGIN = "FAILED_LOGIN";
export const SUCCESSFUL_SIGNUP = "SUCCESSFUL_SIGNUP";

// single product actions
export const POST_NEW_COMMENT = "POST_NEW_COMMENT";
export const SUCCESSFUL_NEW_RATE_SUBMIT = "SUCCESSFUL_NEW_RATE_SUBMIT";
export const SINGLE_PAGE_LOAD = "SINGLE_PAGE_LOAD";
export const USER_RATES_FETCH_SUCCESS = "USER_RATES_FETCH_SUCCESS";

// common sections
export const LOAD_ALL_PRODUCTS = "LOAD_ALL_PRODUCTS";
export const CATEGORY_ITEMS_FETCH_SUCCESS = "CATEGORY_ITEMS_FETCH_SUCCESS";
export const LOAD_DYNAMIC_CONTENT_SUCCESS = "LOAD_DYNAMIC_CONTENT_SUCCESS";

// misc
export const SUBMIT_INVESTMENT_RECORD = "SUBMIT_INVESTMENT_RECORD";
export const SUCCESSFUL_CONTACT_FORM_SUBMIT = "SUCCESSFUL_CONTACT_FORM_SUBMIT";

// profile actions
export const FETCH_PROFILE_REQUEST = "FETCH_PROFILE_REQUEST";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const FETCH_PROFILE_FAIL = "FETCH_PROFILE_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";